/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("de.themoep.randomteleport.java-conventions")
}

dependencies {
    implementation(project(":randomteleport-hook"))
    compileOnly(libs.griefprevention)
    compileOnly(libs.spigot.api)
}

group = "de.themoep.randomteleport.pluginhook"
description = "griefprevention"
